show_alarm_buttons:
  name: "Näytä hälytyspainikkeet"
  initial: off
  icon: mdi:alert-outline

perimeter_notifications:
  name: "Kuorivalvonta"
  initial: on
  icon: mdi:vector-square
motion_notify:
  name: "Liikeilmoitus"
  icon: mdi:bell-outline

guests:
  name: "Guests"
  icon: mdi:human-capacity-increase
